[build]
base = "frontend"
command = "npm install --no-audit --no-fund && npm run build"
publish = "build"   # <-- ajustado para o seu caso

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


