services:
- type: web
  name: emotion-api
  runtime: python
  pythonVersion: 3.11.9
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn fastapi_emotion:app --host 0.0.0.0 --port $PORT

