services:
  - type: web
    name: matchapi
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: SCORE_LIMIAR
        value: "0.75"
      - key: MODEL_NAME
        value: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
