[server]
maxUploadSize = 400 # Max file size for uploads in MB

---

# Otimizações de performance
# [scheduler] maxMessageSize has been removed and must be deleted.

# Cache mais agressivo
[runner]
magicEnabled = false # Disables the automatic rerun when a variable changes.

[global]
developmentMode = false # Ensures max performance (Disables various checks).

