[aws]
aws_access_key_id = "AKIA2HELNK7QI463JUGO"
aws_secret_access_key = "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"
region_name = "us-east-2"
bucket = "datathon-recrutai" # <--- CORRIGIDO! A aspa fechando a string estava faltando.

# O código usará o bucket e a região acima para acessar os dados.
CANDIDATOS_CSV_URL="s3://datathon-recruta/data/applicants_clean.csv"
VAGAS_CSV_URL="s3://datathon-recruta/data/vagas_clean.csv"

# 3. Chaves (caminhos) dos Embeddings no S3
CAND_EMB_S3_KEY="data/embeddings/candidatos.npy"
CAND_META_S3_KEY="data/embeddings/candidatos.meta.json"
VAGA_EMB_S3_KEY="data/embeddings/vagas.npy"
VAGA_META_S3_KEY="data/embeddings/vagas.meta.json"